### ISSUE TITLE
reduce logging overhead with disabled logging

### ISSUE THREAD

**Issue by torbjoernk** [torbjoernk/PFASST#14]
Performance analysis has shown that even logging is disabled at compile time, the compiler still produces a lot of string related instructions.
This should be reduced probably in collaboration with the maintainer of easyloggingpp.

**Comment by f-koehler** [comment]
A solution might be not use the CV_LOG macro. Instead one could use a macro that wraps around CV_LOG but creates a list type from all log components. If logging is enabled this list would be printed with easylogging++ but when disabled an empty operator<< would be used. The compiler will probably optimize this to nop.

I will tinker with this.

**Comment by torbjoernk** [comment]
You might want to look into easyloggingpp's dealing with `LOG(DEBUG)` and `NDEBUG` PP flag. I.e. disabling of debug logging when compiling without `-g` option.

**Comment by f-koehler** [comment]
I will have a look at this as well.

So far I came up with this:

``` c++
#ifndef METALOG_HPP_
#define METALOG_HPP_

#include <ostream>
#include <utility>

namespace metalog {

    struct None {};

    template<typename First, typename Second>
    struct Pair {
        First  first;
        Second second;
    };

    template<typename List>
    struct Data {
        List list;
    };

    template<typename Head, typename Element>
    constexpr Data<Pair<Head, const Element&>> operator<<(Data<Head>&& head, Element&& element) {
        return {{ std::forward<Head>(head.list), std::forward<Element>(element) }};
    }

    template<typename Head, std::size_t N>
    constexpr Data<Pair<Head, const char*>> operator<<(Data<Head>&& head, const char (&element)[N]) {
        return {{ std::forward<Head>(head.list), element }};
    }

    inline void print(std::ostream&, None) {}

#ifndef METALOG_NOLOG
    template<typename Stream, typename Head, typename Tail>
    void print(Stream &strm, const Pair<Head, Tail>&& data) {
        print(strm, std::move(data.first));
        strm << data.second;
    }
#else
    template<typename Stream, typename... Args>
    void print(Stream& strm, Args... args) {
    }
#endif

    template<typename Stream, typename List>
    void log(Stream& strm, Data<List>&& data) {
        print(strm, std::move(data.list));
    }

}

#define METALOG_LOG(strm, x) \
    (metalog::log(strm, metalog::Data<metalog::None>() << x))


#endif
```

This could be wrapped around CV_LOG calls

P.S. I might also to override for io manipulators

**Comment by f-koehler** [comment]
Compiling without `-g` isn't really an option as I still want to profile the code and see function names/source code.

**Comment by torbjoernk** [comment]
I just meant, that it would be nice to see whether the debug logs are also causing the string handling in optimized builds. Though I admit, that it might be hard to track that down without compiling with `-g`. However, you can temporarily define `#define NDEBUG` before including easylogging.

**Comment by f-koehler** [comment]
This does not prevent the calls to `std::to_string`

**Comment by f-koehler** [comment]
I tested/benchmarked my approach (see [gist](https://gist.github.com/f-koehler/881d78c80c890ee9c137)).

Applying this method to all logging calls in IMEX::sweep reduced the number of std::to_string calls greatly and also resulted in a ~8% speedup. See this [branch](https://github.com/f-koehler/PFASST/tree/experiment/metalog)
