### ISSUE TITLE
Rename things

### ISSUE THREAD

**Issue by f-koehler** [torbjoernk/PFASST#23]
I am bad at naming things. So these to things might need a new name:
- [x] metalog and its classes: I think metalog might not be the best name but was the first thing I came up with. I chose the class names in `metalog.hpp` as I find them to fit the function of the classes. But maybe you think differently.
- [x] In the new way the `pfasst_WITH_SCOREP` option works it allows to set arbitrary wrappers for the compile command using the `PREP` environment variable. Maybe it should be an independent option and named something like `pfasst_WITH_EXTRA_WRAPPER`.

**Comment by torbjoernk** [comment]
1) I'll look into that later. Low priority.

2) I'm fine going with `pfasst_WITH_EXTRA_WRAPPER`

**Comment by f-koehler** [comment]
This issue has been resolved.
